services:
  homehub-client:
    container_name: homehub-client
    build:
      context: ..
      dockerfile: Dockerfile
    image: homehub-client:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - homehub-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  homehub-network:
    name: homehub-network
    external: true