server {

    listen 80;
    server_name home.greefob.ru;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    client_max_body_size 20M;

    server_tokens off;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;

    gzip_types
        text/plain
        text/css
        application/javascript
        application/json
        image/svg+xml;

    location / {

        try_files $uri $uri/ /index.html;

    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}