name: Deploy Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "[DEV] Deploying development..."
